import { Injectable } from '@angular/core';
import { environment } from '../environments/environment';
import { createClient, ChainModifiers } from 'contentful';
// Import the types generated by contentful-ts-generator
import {
	TypeArticlePage,
	TypeArticlePageSkeleton,
} from '../contentfulmodels/contentful-types.ts';

// Get configuration from Angular environment
const CONFIG = {
	space: environment.SPACE_ID ?? '',
	accessToken: environment.CONTENT_DELIVERY_API_KEY ?? '',
	testEntryId: environment.TEST_ENTRY_ID ?? '',
};

@Injectable({
	providedIn: 'root',
})
export class ContentfulService {
	private readonly _contentfulClient = createClient({
		space: CONFIG.space,
		accessToken: CONFIG.accessToken,
	});

	constructor() {}

	getEntries(): void {
		this._contentfulClient
			.getEntry<TypeArticlePageSkeleton>(CONFIG.testEntryId)
			.then((response) => console.log(response))
			.catch(console.error);
	}

	getPage(query?: object): Promise<TypeArticlePage<ChainModifiers>> {
		return this._contentfulClient
			.getEntry<TypeArticlePageSkeleton>(CONFIG.testEntryId)
			.then((res) => res as TypeArticlePage<ChainModifiers>);
	}
}
